-- =====================================================
-- FIX SCHEMA ISSUES
-- =====================================================

-- 1. Fix PRODUCTOS ID (Make it auto-increment)
ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- Sync the sequence to the current max ID so next insert doesn't clash
SELECT setval(pg_get_serial_sequence('public.productos', 'id'), COALESCE(max(id), 0) + 1, false) FROM public.productos;

-- 2. Fix VENTAS ID
ALTER TABLE public.ventas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.ventas', 'id'), COALESCE(max(id), 0) + 1, false) FROM public.ventas;

-- 3. Fix SERVICIOS ID
ALTER TABLE public.servicios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.servicios', 'id'), COALESCE(max(id), 0) + 1, false) FROM public.servicios;

-- 4. Fix HORARIOS (Fix types and constraints)
-- 'closed' should be boolean, not text
ALTER TABLE public.horarios ALTER COLUMN closed TYPE boolean USING closed::boolean;

-- 'open' and 'close' can stay text, but ensure not null default empty
ALTER TABLE public.horarios ALTER COLUMN open SET DEFAULT '';
ALTER TABLE public.horarios ALTER COLUMN close SET DEFAULT '';
ALTER TABLE public.horarios ALTER COLUMN closed SET DEFAULT false;

-- 5. Re-apply RLS Policies (CSV import often skips them)
alter table productos enable row level security;
alter table ventas enable row level security;
alter table servicios enable row level security;
alter table horarios enable row level security;

-- Public read policies
create policy "public can read productos" on public.productos for select to anon using (true);
create policy "public can read ventas" on public.ventas for select to anon using (true);
create policy "public can read servicios" on public.servicios for select to anon using (true);
create policy "public can read horarios" on public.horarios for select to anon using (true);

-- Authenticated write policies
create policy "authenticated can all productos" on public.productos for all to authenticated using (true);
create policy "authenticated can all ventas" on public.ventas for all to authenticated using (true);
create policy "authenticated can all servicios" on public.servicios for all to authenticated using (true);
create policy "authenticated can all horarios" on public.horarios for all to authenticated using (true);
